language: node_js
node_js: 5
env:
  APP_NAME=nginx-rtmp-frontend
  ELECTRON_VER=0.35.1
before_script:
  - npm i -g gulp
before_deploy:
  - npm i -g electron-packager
  - ./pack.sh
deploy:
  provider: releases
  file:
    - $APP_NAME-win.zip
    - $APP_NAME-osx.zip
  on:
    tags: true
