sudo: false
addons:
  apt:
    packages:
    - mono-devel
    - wine
language: node_js
node_js: 5
env:
  APP_NAME=nginx-rtmp-frontend
  ELECTRON_VER=0.35.1
before_script:
  - npm i -g gulp
  - npm i -g grunt-cli
  - npm i -g electron-packager
before_deploy:
  - ./pack.sh
deploy:
  provider: releases
  file:
    - installer32/Setup.exe
    - $APP_NAME-win.zip
    - $APP_NAME-osx.zip
  on:
    tags: true
