language: node_js
node_js: 5
env:
  APP_NAME=nginx-rtmp-frontend
  ELECTRON_VER=0.35.1
before_script:
  - npm install gulp
before_deploy:
  - ./pack.sh
  - rvm install 2.0.0
  - rvm use 2.0.0
deploy:
  provider: releases
  file:
    - $APP_NAME-win.zip
    - $APP_NAME-osx.zip
  on:
    tags: true
