environment:
  nodejs_version: "5.1.0"

install:
  - git submodule update --init
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm i -g gulp
  - npm i -g grunt-cli
  - npm i -g electron-packager

build: off

test_script:
  - node --version
  - npm --version
  - npm test

before_deploy:
  - set APP_NAME=nginx-rtmp-frontend
  - set ELECTRON_VER=0.35.1
  - copy scripts\* .
  - copy.bat
  - packwin.bat
  - packosx.bat

deploy:
  provider: GitHub
  auth_token:
    secure: TyOsDTpQJ+hMXU5/rtlKTluUS4XKw2+QSyFGnpMyYCy8WLEc2xSfortNiXayk0KF
  artifact: /.*\.(exe|zip)/
  on:
    appveyor_repo_tag: true
